# Generated by Django 3.2 on 2021-04-30 21:35

from django.db import migrations
import django_thumbs.fields
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_thumbs.fields.ImageThumbsField(blank=True, null=True, sizes=({'code': 'thumb', 'resize': 'crop', 'wxh': '125x125'},), upload_to=''),
        ),
    ]
