# Generated by Django 3.2 on 2021-04-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210425_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='wendy-and-peter-pan', editable=False, max_length=160, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tagline',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
