# Generated by Django 3.2 on 2021-05-24 14:38

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_venue_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='GB', max_length=2, null=True),
        ),
    ]
