# Generated by Django 3.2 on 2021-05-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0002_auto_20210512_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='data',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='county',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='town_or_city',
        ),
    ]
