# Generated by Django 3.2 on 2021-05-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0003_auto_20210513_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_bag',
            new_name='original_basket',
        ),
    ]
