# Generated by Django 3.2 on 2021-05-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0004_tickettemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketTemplate',
        ),
    ]
