# Generated by Django 3.2 on 2021-05-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0004_tickettemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
