# Generated by Django 3.2 on 2021-05-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0005_alter_tickettemplate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='text_color',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
